const Portfolio_data = [
    {
      id: 1,
      category: "Website Development",
      totalLike: "600",
      title: "Website for an architectural firm",
      image: "./image/portfolio-01.jpg",
      gitHub : 'https://github.com/islam-khalil0/website_architectural',
      liveSite : "https://islam-khalil0.github.io/website_architectural/",
    },
    {
      id: 2,
      category: "Website Development",
      totalLike: "750",
      title: "Mobile application website",
      image: "./image/portfolio-02.jpg",
      gitHub : 'https://github.com/islam-khalil0/Mobile-application-website',
      liveSite : "https://islam-khalil0.github.io/Mobile-application-website/",
    },
    {
      id: 3,
      category: "Website Development",
      totalLike: "630",
      title: "photo editor website",
      image: "./image/portfolio-03.jpg",
      gitHub : 'https://github.com/islam-khalil0/photo-editor',
      liveSite : "https://islam-khalil0.github.io/photo-editor/",
    },
    {
      id: 4,
      category: "Website Development",
      totalLike: "360",
      title: "control Board",
      image: "./image/portfolio-04.jpg",
      gitHub : 'https://github.com/islam-khalil0/dashboard-design-',
      liveSite : "https://islam-khalil0.github.io/dashboard-design-/",
    },
    {
      id: 5,
      category: "Website Development",
      totalLike: "280",
      title: "Online course website",
      image: "./image/portfolio-05.jpg",
      gitHub : 'https://github.com/islam-khalil0/courses-website',
      liveSite : "https://islam-khalil0.github.io/courses-website/",
    },
    {
      id: 6,
      category: "Website Development",
      totalLike: "690",
      title: "CRUDS Project",
      image: "./image/portfolio-06.jpg",
      gitHub : 'https://github.com/islam-khalil0/cruds-project-',
      liveSite : "https://islam-khalil0.github.io/cruds-project-/",
    },
  ]
  export default Portfolio_data
  